version: 2
updates:
  - package-ecosystem: "npm" # or "bundler", "pip", etc.
    directory: "/" # Location of your package manifests
    schedule:
      interval: "daily" # or "weekly", "monthly"
      time: "03:00" # 12:00 JST (UTC+9)
      timezone: "Asia/Tokyo"
